### PR TITLE
fixes #6

### LINKED ISSUE #6: Not working in windows after reload
When I install this extension everything works great until I close Brackets.

After I close and reopen Brackets this extension no longer works.  My other extensions continue to work but not this one.  if I uninstall this package and reinstall... it starts working again.

OS:  Windows 7 Pro 
Brackets: Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 

Tonight I plan on testing this on Ubuntu 14.04.  Will see if this issue is isolated to the OS or not.

### PR DESCRIPTION
**Pull request by blah73**
fixes issue where extension wouldn't work after brackets restart

### CODE REVIEW

**Comment by blah73** [comment]
I'm new to brackets and writing extensions but this alleviated my issue and seemed to have no adverse side effects.

**Comment by MrBodira** [comment]
Thanks blah73, your fix solved the problem.

**Comment by bryanjhv** [comment]
It seems Brackets is changing its API, but the problem all are facing is after a PR I merged... Can you try db6d41a598d43bd8eceeb0223ed819ad9eda7611 to see if it is due to that?
BTW, as my comment in #6 states, it is working fine for me.

**Comment by blah73** [comment]
Yes!  db6d41a works great for me!

**Comment by bryanjhv** [comment]
Thanks for the update. I also noticed a `Cannot call method 'on' of null` error with my extension after PR #4. The PR is right, but some things broke.
Sorry can't accept yours, but the Brackets API states the appReady method must be called, and accepting the changes means maybe in future releases another bug.

**Comment by blah73** [comment]
Makes sense to me. Sounds like #4 needs a debug.  I just briefly looked at a couple other extensions and didn't see appReady called.

**Comment by bryanjhv** [comment]
Maybe you're right according to https://github.com/adobe/brackets/wiki/Brackets-Development-How-Tos#application-init . I'll still try your PR and make sure it works, ok? :smiley:

**Comment by bryanjhv** [comment]
It's now merged :smile: Thanks! There was a need to remove `$` from globals comment, and the `AppInit` require, also some `_getOption` stuff instead of hardcoding CodeMirror.

**Pull request merged**
